
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SMWRealm_Example' do
  platform :ios, '7.0'
  pod "SMWRealm", :path => "../"
  pod 'Realm'
end


target 'SMWRealm_Tests' do
  platform :ios, '7.0'
  pod "SMWRealm", :path => "../"
  pod 'Realm'

  pod 'Specta'
  pod 'Expecta'
end
